server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    # url: jdbc:mysql://132.232.104.247:3306/tensquare_blog?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    # 不显式设置字符集，集成服务器配置，服务器的mysql已经设置为utf8mb4
    url: jdbc:mysql://132.232.104.247:3306/api_info?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: '!QAZ2wsx'
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      stat-view-servlet:
        allow: true
  # redis配置
  redis:
    host: 132.232.104.247
    port: 6379
    password: admin # 默认为空
    database: 1
    pool:
      max-active: 20
      max-wait: -1 # 没有限制
      max-idle: 8
      min-idle: 0
    timeout: 0
    testOnBorrow: true
# mybatis配置
mybatis:
  type-aliases-package: com.wx.mini.pojo
  mapper-locations: classpath*:mapper/*.xml
# 通用mapper配置
mapper:
  mappers: com.wx.mini.utils.MyMapper
  not-empty: false
  identity: MYSQL
#分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  params: count=countsql
  supportMethodsArguments: true
logging:
  level:
    root: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) [%thread] %clr(%-5level) %logger{50}[%L] -%msg%n"
# 其他配置
user:
  upload:
    face:
      fileSpace: /Users/alan.chen/Desktop/dmsData
ffmpeg:
  path: /Users/alan.chen/Documents/notes/ffmpeg
# api url
api:
  url:
    earthlySweetApi: https://api.lovelive.tools/api/SweetNothings/Serialization/:serializationType/:count
    rainbowFartApi: https://chp.shadiao.app/api.php
kqHost: ws://106.14.60.133:25303
robot:
  weather:
    url: https://www.mxnzp.com/api/weather/current/咸阳市
  robotOption: 1
  qingyunke:
    api: http://api.qingyunke.com/api.php?key=free&appid=0&msg=%s